package com.inventory.config;

import com.inventory.model.Ciudad;
import com.inventory.repository.CiudadRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

import java.util.Arrays;
import java.util.List;
import java.util.Set;

/**
 * Pobla la tabla ciudades con los municipios de Colombia usando códigos DANE reales.
 * Solo los municipios de la Costa Caribe y San Andrés inician con activo=true.
 *
 * Departamentos activos (costa):
 *   Atlántico (08), Bolívar (13), Magdalena (47), Cesar (20),
 *   Córdoba (23), Sucre (70), La Guajira (44), San Andrés (88)
 */
@Component
@Order(5)
public class CiudadInitializer implements CommandLineRunner {

    private static final Logger log = LoggerFactory.getLogger(CiudadInitializer.class);

    /** Códigos DANE de departamentos que inician activos (Costa Caribe + San Andrés). */
    private static final Set<String> DEPTOS_ACTIVOS = Set.of(
        "08", // Atlántico
        "13", // Bolívar
        "47", // Magdalena
        "20", // Cesar
        "23", // Córdoba
        "70", // Sucre
        "44", // La Guajira
        "88"  // San Andrés y Providencia
    );

    @Autowired
    private CiudadRepository ciudadRepository;

    @Override
    public void run(String... args) throws Exception {
        long existing = ciudadRepository.count();
        if (existing > 0) {
            log.info("CiudadInitializer: {} ciudades ya en BD, omitiendo.", existing);
            return;
        }

        List<Ciudad> ciudades = buildCiudades();
        ciudadRepository.saveAll(ciudades);
        long activas = ciudades.stream().filter(Ciudad::isActivo).count();
        log.info("CiudadInitializer: {} municipios cargados ({} activos).", ciudades.size(), activas);
    }

    private boolean esActivo(String cod) {
        return DEPTOS_ACTIVOS.contains(cod.substring(0, 2));
    }

    private Ciudad c(String cod, String nombre, String depto) {
        return new Ciudad(cod, nombre, depto, esActivo(cod));
    }

    private List<Ciudad> buildCiudades() {
        return Arrays.asList(
            // ── Amazonas (91) ──────────────────────────────────────────
            c("91001","Leticia","Amazonas"),
            c("91263","El Encanto","Amazonas"),
            c("91405","La Chorrera","Amazonas"),
            c("91407","La Pedrera","Amazonas"),
            c("91430","La Victoria","Amazonas"),
            c("91460","Mirití-Paraná","Amazonas"),
            c("91530","Puerto Alegría","Amazonas"),
            c("91536","Puerto Arica","Amazonas"),
            c("91540","Puerto Nariño","Amazonas"),
            c("91669","Puerto Santander","Amazonas"),
            c("91798","Tarapacá","Amazonas"),
            // ── Antioquia (05) ────────────────────────────────────────
            c("05001","Medellín","Antioquia"),
            c("05002","Abejorral","Antioquia"),
            c("05004","Abriaquí","Antioquia"),
            c("05021","Alejandría","Antioquia"),
            c("05030","Amagá","Antioquia"),
            c("05031","Amalfi","Antioquia"),
            c("05034","Andes","Antioquia"),
            c("05036","Angelópolis","Antioquia"),
            c("05038","Angostura","Antioquia"),
            c("05040","Anorí","Antioquia"),
            c("05044","Anzá","Antioquia"),
            c("05045","Apartadó","Antioquia"),
            c("05051","Arboletes","Antioquia"),
            c("05055","Argelia","Antioquia"),
            c("05059","Armenia","Antioquia"),
            c("05079","Barbosa","Antioquia"),
            c("05086","Belmira","Antioquia"),
            c("05088","Bello","Antioquia"),
            c("05091","Betania","Antioquia"),
            c("05093","Betulia","Antioquia"),
            c("05101","Ciudad Bolívar","Antioquia"),
            c("05107","Briceño","Antioquia"),
            c("05113","Buriticá","Antioquia"),
            c("05120","Cáceres","Antioquia"),
            c("05125","Caicedo","Antioquia"),
            c("05129","Caldas","Antioquia"),
            c("05134","Campamento","Antioquia"),
            c("05138","Cañasgordas","Antioquia"),
            c("05142","Caracolí","Antioquia"),
            c("05145","Caramanta","Antioquia"),
            c("05147","Carepa","Antioquia"),
            c("05148","El Carmen de Viboral","Antioquia"),
            c("05150","Carolina","Antioquia"),
            c("05154","Caucasia","Antioquia"),
            c("05172","Chigorodó","Antioquia"),
            c("05190","Cisneros","Antioquia"),
            c("05197","Cocorná","Antioquia"),
            c("05206","Concepción","Antioquia"),
            c("05209","Concordia","Antioquia"),
            c("05212","Copacabana","Antioquia"),
            c("05234","Dabeiba","Antioquia"),
            c("05237","Don Matías","Antioquia"),
            c("05240","Ebéjico","Antioquia"),
            c("05250","El Bagre","Antioquia"),
            c("05264","Entrerríos","Antioquia"),
            c("05266","Envigado","Antioquia"),
            c("05282","Fredonia","Antioquia"),
            c("05284","Frontino","Antioquia"),
            c("05306","Giraldo","Antioquia"),
            c("05308","Girardota","Antioquia"),
            c("05310","Gómez Plata","Antioquia"),
            c("05313","Granada","Antioquia"),
            c("05315","Guadalupe","Antioquia"),
            c("05318","Guarne","Antioquia"),
            c("05321","Guatapé","Antioquia"),
            c("05347","Heliconia","Antioquia"),
            c("05353","Hispania","Antioquia"),
            c("05360","Itagüí","Antioquia"),
            c("05361","Ituango","Antioquia"),
            c("05364","Jardín","Antioquia"),
            c("05368","Jericó","Antioquia"),
            c("05376","La Ceja","Antioquia"),
            c("05380","La Estrella","Antioquia"),
            c("05390","La Pintada","Antioquia"),
            c("05400","La Unión","Antioquia"),
            c("05411","Liborina","Antioquia"),
            c("05425","Maceo","Antioquia"),
            c("05440","Marinilla","Antioquia"),
            c("05467","Montebello","Antioquia"),
            c("05475","Murindó","Antioquia"),
            c("05480","Mutatá","Antioquia"),
            c("05483","Nariño","Antioquia"),
            c("05490","Necoclí","Antioquia"),
            c("05495","Nechí","Antioquia"),
            c("05501","Olaya","Antioquia"),
            c("05541","Peñol","Antioquia"),
            c("05543","Peque","Antioquia"),
            c("05576","Pueblorrico","Antioquia"),
            c("05579","Puerto Berrío","Antioquia"),
            c("05585","Puerto Nare","Antioquia"),
            c("05591","Puerto Triunfo","Antioquia"),
            c("05604","Remedios","Antioquia"),
            c("05607","Retiro","Antioquia"),
            c("05615","Rionegro","Antioquia"),
            c("05628","Sabanalarga","Antioquia"),
            c("05631","Sabaneta","Antioquia"),
            c("05642","Salgar","Antioquia"),
            c("05647","San Andrés de Cuerquía","Antioquia"),
            c("05649","San Carlos","Antioquia"),
            c("05652","San Francisco","Antioquia"),
            c("05656","San Jerónimo","Antioquia"),
            c("05658","San José de la Montaña","Antioquia"),
            c("05659","San Juan de Urabá","Antioquia"),
            c("05660","San Luis","Antioquia"),
            c("05664","San Pedro de los Milagros","Antioquia"),
            c("05665","San Pedro de Urabá","Antioquia"),
            c("05667","San Rafael","Antioquia"),
            c("05670","San Roque","Antioquia"),
            c("05674","San Vicente Ferrer","Antioquia"),
            c("05679","Santa Bárbara","Antioquia"),
            c("05686","Santa Rosa de Osos","Antioquia"),
            c("05690","Santo Domingo","Antioquia"),
            c("05697","El Santuario","Antioquia"),
            c("05736","Segovia","Antioquia"),
            c("05756","Sonsón","Antioquia"),
            c("05761","Sopetrán","Antioquia"),
            c("05789","Támesis","Antioquia"),
            c("05790","Tarazá","Antioquia"),
            c("05792","Tarso","Antioquia"),
            c("05809","Titiribí","Antioquia"),
            c("05819","Toledo","Antioquia"),
            c("05837","Turbo","Antioquia"),
            c("05842","Uramita","Antioquia"),
            c("05847","Urrao","Antioquia"),
            c("05854","Valdivia","Antioquia"),
            c("05856","Valparaíso","Antioquia"),
            c("05858","Vegachí","Antioquia"),
            c("05861","Venecia","Antioquia"),
            c("05873","Vigía del Fuerte","Antioquia"),
            c("05885","Yalí","Antioquia"),
            c("05887","Yarumal","Antioquia"),
            c("05890","Yolombó","Antioquia"),
            c("05893","Yondó","Antioquia"),
            c("05895","Zaragoza","Antioquia"),
            // ── Arauca (81) ──────────────────────────────────────────
            c("81001","Arauca","Arauca"),
            c("81065","Arauquita","Arauca"),
            c("81220","Cravo Norte","Arauca"),
            c("81300","Fortul","Arauca"),
            c("81591","Puerto Rondón","Arauca"),
            c("81736","Saravena","Arauca"),
            c("81794","Tame","Arauca"),
            // ── Atlántico (08) — ACTIVO ───────────────────────────────
            c("08001","Barranquilla","Atlántico"),
            c("08078","Baranoa","Atlántico"),
            c("08137","Campo de la Cruz","Atlántico"),
            c("08141","Candelaria","Atlántico"),
            c("08296","Galapa","Atlántico"),
            c("08372","Juan de Acosta","Atlántico"),
            c("08421","Luruaco","Atlántico"),
            c("08433","Malambo","Atlántico"),
            c("08436","Manatí","Atlántico"),
            c("08520","Palmar de Varela","Atlántico"),
            c("08549","Piojó","Atlántico"),
            c("08558","Polonuevo","Atlántico"),
            c("08560","Ponedera","Atlántico"),
            c("08573","Puerto Colombia","Atlántico"),
            c("08606","Repelón","Atlántico"),
            c("08634","Sabanagrande","Atlántico"),
            c("08638","Sabanalarga","Atlántico"),
            c("08675","Santa Lucía","Atlántico"),
            c("08685","Santo Tomás","Atlántico"),
            c("08758","Soledad","Atlántico"),
            c("08770","Suán","Atlántico"),
            c("08832","Tubará","Atlántico"),
            c("08849","Usiacurí","Atlántico"),
            // ── Bolívar (13) — ACTIVO ─────────────────────────────────
            c("13001","Cartagena de Indias","Bolívar"),
            c("13006","Achí","Bolívar"),
            c("13030","Altos del Rosario","Bolívar"),
            c("13042","Arenal","Bolívar"),
            c("13052","Arjona","Bolívar"),
            c("13062","Arroyohondo","Bolívar"),
            c("13074","Barranco de Loba","Bolívar"),
            c("13140","Calamar","Bolívar"),
            c("13160","Cantagallo","Bolívar"),
            c("13188","Cicuco","Bolívar"),
            c("13212","Córdoba","Bolívar"),
            c("13222","Clemencia","Bolívar"),
            c("13244","El Carmen de Bolívar","Bolívar"),
            c("13248","El Guamo","Bolívar"),
            c("13268","El Peñón","Bolívar"),
            c("13300","Hatillo de Loba","Bolívar"),
            c("13430","Magangué","Bolívar"),
            c("13433","Mahates","Bolívar"),
            c("13440","Margarita","Bolívar"),
            c("13458","María la Baja","Bolívar"),
            c("13468","Mompox","Bolívar"),
            c("13473","Morales","Bolívar"),
            c("13490","Norosí","Bolívar"),
            c("13549","Pinillos","Bolívar"),
            c("13580","Regidor","Bolívar"),
            c("13600","Río Viejo","Bolívar"),
            c("13620","San Cristóbal","Bolívar"),
            c("13647","San Estanislao","Bolívar"),
            c("13650","San Fernando","Bolívar"),
            c("13654","San Jacinto","Bolívar"),
            c("13655","San Jacinto del Cauca","Bolívar"),
            c("13657","San Juan Nepomuceno","Bolívar"),
            c("13667","San Martín de Loba","Bolívar"),
            c("13670","San Pablo","Bolívar"),
            c("13673","Santa Catalina","Bolívar"),
            c("13683","Santa Rosa","Bolívar"),
            c("13688","Santa Rosa del Sur","Bolívar"),
            c("13744","Simití","Bolívar"),
            c("13760","Soplaviento","Bolívar"),
            c("13780","Talaigua Nuevo","Bolívar"),
            c("13810","Tiquisio","Bolívar"),
            c("13836","Turbaco","Bolívar"),
            c("13838","Turbaná","Bolívar"),
            c("13873","Villanueva","Bolívar"),
            c("13894","Zambrano","Bolívar"),
            // ── Boyacá (15) ───────────────────────────────────────────
            c("15001","Tunja","Boyacá"),
            c("15022","Almeida","Boyacá"),
            c("15047","Aquitania","Boyacá"),
            c("15051","Arcabuco","Boyacá"),
            c("15087","Belén","Boyacá"),
            c("15090","Berbeo","Boyacá"),
            c("15092","Betéitiva","Boyacá"),
            c("15097","Boavita","Boyacá"),
            c("15104","Boyacá","Boyacá"),
            c("15106","Briceño","Boyacá"),
            c("15109","Buenavista","Boyacá"),
            c("15114","Busbanzá","Boyacá"),
            c("15131","Caldas","Boyacá"),
            c("15135","Campohermoso","Boyacá"),
            c("15162","Cerinza","Boyacá"),
            c("15172","Chinavita","Boyacá"),
            c("15176","Chiquinquirá","Boyacá"),
            c("15180","Chíquiza","Boyacá"),
            c("15183","Chiscas","Boyacá"),
            c("15185","Chita","Boyacá"),
            c("15187","Chitaraque","Boyacá"),
            c("15189","Chivatá","Boyacá"),
            c("15204","Cómbita","Boyacá"),
            c("15212","Coper","Boyacá"),
            c("15215","Corrales","Boyacá"),
            c("15218","Covarachía","Boyacá"),
            c("15223","Cubará","Boyacá"),
            c("15224","Cucaita","Boyacá"),
            c("15226","Cuítiva","Boyacá"),
            c("15232","Chíquiza","Boyacá"),
            c("15236","Duitama","Boyacá"),
            c("15238","El Cocuy","Boyacá"),
            c("15244","El Espino","Boyacá"),
            c("15248","Firavitoba","Boyacá"),
            c("15272","Floresta","Boyacá"),
            c("15276","Gachantivá","Boyacá"),
            c("15293","Gameza","Boyacá"),
            c("15296","Garagoa","Boyacá"),
            c("15299","Guacamayas","Boyacá"),
            c("15317","Guateque","Boyacá"),
            c("15322","Guayatá","Boyacá"),
            c("15325","Güicán","Boyacá"),
            c("15332","Iza","Boyacá"),
            c("15362","Jenesano","Boyacá"),
            c("15367","Jericó","Boyacá"),
            c("15380","La Capilla","Boyacá"),
            c("15401","La Victoria","Boyacá"),
            c("15403","La Uvita","Boyacá"),
            c("15407","Villa de Leyva","Boyacá"),
            c("15425","Labranzagrande","Boyacá"),
            c("15442","Macanal","Boyacá"),
            c("15455","Maripí","Boyacá"),
            c("15464","Miraflores","Boyacá"),
            c("15469","Mongua","Boyacá"),
            c("15476","Monguí","Boyacá"),
            c("15480","Moniquirá","Boyacá"),
            c("15491","Motavita","Boyacá"),
            c("15494","Muzo","Boyacá"),
            c("15500","Nobsa","Boyacá"),
            c("15507","Nuevo Colón","Boyacá"),
            c("15511","Oicatá","Boyacá"),
            c("15514","Otanche","Boyacá"),
            c("15516","Pachavita","Boyacá"),
            c("15518","Páez","Boyacá"),
            c("15522","Paipa","Boyacá"),
            c("15531","Pajarito","Boyacá"),
            c("15533","Panqueba","Boyacá"),
            c("15537","Pauna","Boyacá"),
            c("15542","Paya","Boyacá"),
            c("15547","Paz de Río","Boyacá"),
            c("15550","Pesca","Boyacá"),
            c("15572","Pisba","Boyacá"),
            c("15580","Puerto Boyacá","Boyacá"),
            c("15599","Quípama","Boyacá"),
            c("15600","Ramiriquí","Boyacá"),
            c("15621","Ráquira","Boyacá"),
            c("15632","Rondón","Boyacá"),
            c("15638","Saboyá","Boyacá"),
            c("15646","Sáchica","Boyacá"),
            c("15660","Samacá","Boyacá"),
            c("15664","San Eduardo","Boyacá"),
            c("15667","San José de Pare","Boyacá"),
            c("15673","San Luis de Gaceno","Boyacá"),
            c("15676","San Mateo","Boyacá"),
            c("15681","San Miguel de Sema","Boyacá"),
            c("15686","San Pablo de Borbur","Boyacá"),
            c("15690","Santana","Boyacá"),
            c("15693","Santa María","Boyacá"),
            c("15696","Santa Rosa de Viterbo","Boyacá"),
            c("15720","Santa Sofía","Boyacá"),
            c("15723","Sativanorte","Boyacá"),
            c("15740","Sativasur","Boyacá"),
            c("15753","Siachoque","Boyacá"),
            c("15757","Soatá","Boyacá"),
            c("15759","Socotá","Boyacá"),
            c("15761","Socha","Boyacá"),
            c("15762","Sogamoso","Boyacá"),
            c("15763","Somondoco","Boyacá"),
            c("15764","Sora","Boyacá"),
            c("15774","Sotaquirá","Boyacá"),
            c("15776","Soracá","Boyacá"),
            c("15778","Susacón","Boyacá"),
            c("15790","Sutamarchán","Boyacá"),
            c("15797","Sutatenza","Boyacá"),
            c("15804","Tasco","Boyacá"),
            c("15808","Tenza","Boyacá"),
            c("15810","Tibaná","Boyacá"),
            c("15814","Tibasosa","Boyacá"),
            c("15816","Tinjacá","Boyacá"),
            c("15820","Tipacoque","Boyacá"),
            c("15822","Toca","Boyacá"),
            c("15832","Tópaga","Boyacá"),
            c("15835","Tota","Boyacá"),
            c("15839","Tununguá","Boyacá"),
            c("15842","Turmequé","Boyacá"),
            c("15861","Tutazá","Boyacá"),
            c("15879","Umbita","Boyacá"),
            c("15897","Ventaquemada","Boyacá"),
            c("15902","Viracachá","Boyacá"),
            c("15910","Zetaquira","Boyacá"),
            // ── Caldas (17) ───────────────────────────────────────────
            c("17001","Manizales","Caldas"),
            c("17013","Aguadas","Caldas"),
            c("17042","Anserma","Caldas"),
            c("17050","Aranzazu","Caldas"),
            c("17088","Belalcázar","Caldas"),
            c("17174","Chinchiná","Caldas"),
            c("17272","Filadelfia","Caldas"),
            c("17380","La Dorada","Caldas"),
            c("17388","La Merced","Caldas"),
            c("17433","Manzanares","Caldas"),
            c("17442","Marmato","Caldas"),
            c("17444","Marquetalia","Caldas"),
            c("17446","Marulanda","Caldas"),
            c("17486","Neira","Caldas"),
            c("17495","Norcasia","Caldas"),
            c("17513","Pácora","Caldas"),
            c("17524","Palestina","Caldas"),
            c("17541","Pensilvania","Caldas"),
            c("17614","Riosucio","Caldas"),
            c("17616","Risaralda","Caldas"),
            c("17653","Salamina","Caldas"),
            c("17662","Samaná","Caldas"),
            c("17665","San José","Caldas"),
            c("17777","Supía","Caldas"),
            c("17867","Victoria","Caldas"),
            c("17873","Villamaría","Caldas"),
            c("17877","Viterbo","Caldas"),
            // ── Caquetá (18) ──────────────────────────────────────────
            c("18001","Florencia","Caquetá"),
            c("18029","Albania","Caquetá"),
            c("18094","Belén de los Andaquíes","Caquetá"),
            c("18150","Cartagena del Chairá","Caquetá"),
            c("18205","Curillo","Caquetá"),
            c("18247","El Doncello","Caquetá"),
            c("18256","El Paujil","Caquetá"),
            c("18410","La Montañita","Caquetá"),
            c("18460","Milán","Caquetá"),
            c("18479","Morelia","Caquetá"),
            c("18592","Puerto Rico","Caquetá"),
            c("18610","San José del Fragua","Caquetá"),
            c("18753","San Vicente del Caguán","Caquetá"),
            c("18756","Solano","Caquetá"),
            c("18785","Solita","Caquetá"),
            c("18860","Valparaíso","Caquetá"),
            // ── Casanare (85) ─────────────────────────────────────────
            c("85001","Yopal","Casanare"),
            c("85010","Aguazul","Casanare"),
            c("85015","Chámeza","Casanare"),
            c("85125","Hato Corozal","Casanare"),
            c("85136","La Salina","Casanare"),
            c("85139","Maní","Casanare"),
            c("85162","Monterrey","Casanare"),
            c("85225","Nunchía","Casanare"),
            c("85230","Orocué","Casanare"),
            c("85250","Paz de Ariporo","Casanare"),
            c("85263","Pore","Casanare"),
            c("85279","Recetor","Casanare"),
            c("85300","Sabanalarga","Casanare"),
            c("85315","Sácama","Casanare"),
            c("85325","San Luis de Palenque","Casanare"),
            c("85400","Támara","Casanare"),
            c("85410","Tauramena","Casanare"),
            c("85430","Trinidad","Casanare"),
            c("85440","Villanueva","Casanare"),
            // ── Cauca (19) ────────────────────────────────────────────
            c("19001","Popayán","Cauca"),
            c("19022","Almaguer","Cauca"),
            c("19050","Argelia","Cauca"),
            c("19075","Balboa","Cauca"),
            c("19100","Bolívar","Cauca"),
            c("19110","Buenos Aires","Cauca"),
            c("19130","Cajibío","Cauca"),
            c("19137","Caldono","Cauca"),
            c("19142","Caloto","Cauca"),
            c("19212","Córdoba","Cauca"),
            c("19256","El Tambo","Cauca"),
            c("19290","Florencia","Cauca"),
            c("19300","Guachené","Cauca"),
            c("19318","Guapí","Cauca"),
            c("19355","Inzá","Cauca"),
            c("19364","Jambaló","Cauca"),
            c("19392","La Sierra","Cauca"),
            c("19397","La Vega","Cauca"),
            c("19418","López de Micay","Cauca"),
            c("19450","Mercaderes","Cauca"),
            c("19455","Miranda","Cauca"),
            c("19473","Morales","Cauca"),
            c("19513","Padilla","Cauca"),
            c("19517","Páez","Cauca"),
            c("19532","Patía","Cauca"),
            c("19533","Piamonte","Cauca"),
            c("19548","Piendamó","Cauca"),
            c("19573","Puerto Tejada","Cauca"),
            c("19585","Puracé","Cauca"),
            c("19622","Rosas","Cauca"),
            c("19693","San Sebastián","Cauca"),
            c("19698","Santander de Quilichao","Cauca"),
            c("19701","Santa Rosa","Cauca"),
            c("19743","Silvia","Cauca"),
            c("19760","Sotara","Cauca"),
            c("19780","Suárez","Cauca"),
            c("19785","Sucre","Cauca"),
            c("19807","Timbío","Cauca"),
            c("19809","Timbiquí","Cauca"),
            c("19821","Toribío","Cauca"),
            c("19824","Totoró","Cauca"),
            c("19845","Villa Rica","Cauca"),
            // ── Cesar (20) — ACTIVO ───────────────────────────────────
            c("20001","Valledupar","Cesar"),
            c("20011","Aguachica","Cesar"),
            c("20013","Agustín Codazzi","Cesar"),
            c("20032","Astrea","Cesar"),
            c("20045","Becerril","Cesar"),
            c("20060","Bosconia","Cesar"),
            c("20175","Chimichagua","Cesar"),
            c("20178","Chiriguaná","Cesar"),
            c("20228","Curumaní","Cesar"),
            c("20238","El Copey","Cesar"),
            c("20250","El Paso","Cesar"),
            c("20295","Gamarra","Cesar"),
            c("20310","González","Cesar"),
            c("20383","La Gloria","Cesar"),
            c("20400","La Jagua de Ibirico","Cesar"),
            c("20443","Manaure Balcón del Cesar","Cesar"),
            c("20517","Pailitas","Cesar"),
            c("20550","Pelaya","Cesar"),
            c("20570","Pueblo Bello","Cesar"),
            c("20614","Río de Oro","Cesar"),
            c("20621","La Paz","Cesar"),
            c("20710","San Alberto","Cesar"),
            c("20750","San Diego","Cesar"),
            c("20770","San Martín","Cesar"),
            c("20787","Tamalameque","Cesar"),
            // ── Chocó (27) ────────────────────────────────────────────
            c("27001","Quibdó","Chocó"),
            c("27006","Acandí","Chocó"),
            c("27025","Alto Baudó","Chocó"),
            c("27050","Atrato","Chocó"),
            c("27073","Bagadó","Chocó"),
            c("27075","Bahía Solano","Chocó"),
            c("27077","Bajo Baudó","Chocó"),
            c("27099","Bojayá","Chocó"),
            c("27135","El Cantón del San Pablo","Chocó"),
            c("27150","Carmen del Darién","Chocó"),
            c("27160","Cértegui","Chocó"),
            c("27205","Condoto","Chocó"),
            c("27245","El Carmen de Atrato","Chocó"),
            c("27250","El Litoral del San Juan","Chocó"),
            c("27361","Istmina","Chocó"),
            c("27372","Juradó","Chocó"),
            c("27413","Lloró","Chocó"),
            c("27425","Medio Atrato","Chocó"),
            c("27430","Medio Baudó","Chocó"),
            c("27450","Medio San Juan","Chocó"),
            c("27491","Nóvita","Chocó"),
            c("27495","Nuquí","Chocó"),
            c("27580","Río Iro","Chocó"),
            c("27600","Río Quito","Chocó"),
            c("27615","Riosucio","Chocó"),
            c("27660","San José del Palmar","Chocó"),
            c("27745","Sipí","Chocó"),
            c("27787","Tadó","Chocó"),
            c("27800","Unguía","Chocó"),
            c("27810","Unión Panamericana","Chocó"),
            // ── Córdoba (23) — ACTIVO ─────────────────────────────────
            c("23001","Montería","Córdoba"),
            c("23068","Ayapel","Córdoba"),
            c("23079","Buenavista","Córdoba"),
            c("23090","Canalete","Córdoba"),
            c("23162","Cereté","Córdoba"),
            c("23168","Chimá","Córdoba"),
            c("23182","Chinú","Córdoba"),
            c("23189","Ciénaga de Oro","Córdoba"),
            c("23300","Cotorra","Córdoba"),
            c("23350","La Apartada","Córdoba"),
            c("23417","Lorica","Córdoba"),
            c("23419","Los Córdobas","Córdoba"),
            c("23464","Momil","Córdoba"),
            c("23466","Montelíbano","Córdoba"),
            c("23500","Moñitos","Córdoba"),
            c("23555","Planeta Rica","Córdoba"),
            c("23570","Pueblo Nuevo","Córdoba"),
            c("23574","Puerto Escondido","Córdoba"),
            c("23580","Puerto Libertador","Córdoba"),
            c("23586","Purísima de la Concepción","Córdoba"),
            c("23660","Sahagún","Córdoba"),
            c("23670","San Andrés de Sotavento","Córdoba"),
            c("23672","San Antero","Córdoba"),
            c("23675","San Bernardo del Viento","Córdoba"),
            c("23678","San Carlos","Córdoba"),
            c("23682","San José de Uré","Córdoba"),
            c("23686","San Pelayo","Córdoba"),
            c("23807","Tierralta","Córdoba"),
            c("23815","Tuchín","Córdoba"),
            c("23855","Valencia","Córdoba"),
            // ── Cundinamarca (25) ─────────────────────────────────────
            c("25001","Agua de Dios","Cundinamarca"),
            c("25019","Albán","Cundinamarca"),
            c("25035","Anapoima","Cundinamarca"),
            c("25040","Anolaima","Cundinamarca"),
            c("25053","Arbeláez","Cundinamarca"),
            c("25086","Beltrán","Cundinamarca"),
            c("25095","Bituima","Cundinamarca"),
            c("25099","Bojacá","Cundinamarca"),
            c("25120","Cabrera","Cundinamarca"),
            c("25123","Cachipay","Cundinamarca"),
            c("25126","Cajicá","Cundinamarca"),
            c("25148","Caparrapí","Cundinamarca"),
            c("25151","Cáqueza","Cundinamarca"),
            c("25154","Carmen de Carupa","Cundinamarca"),
            c("25168","Chaguaní","Cundinamarca"),
            c("25175","Chía","Cundinamarca"),
            c("25178","Chipaque","Cundinamarca"),
            c("25181","Choachí","Cundinamarca"),
            c("25183","Chocontá","Cundinamarca"),
            c("25200","Cogua","Cundinamarca"),
            c("25214","Cota","Cundinamarca"),
            c("25224","Cucunubá","Cundinamarca"),
            c("25245","El Colegio","Cundinamarca"),
            c("25258","El Peñón","Cundinamarca"),
            c("25260","El Rosal","Cundinamarca"),
            c("25269","Facatativá","Cundinamarca"),
            c("25279","Fomeque","Cundinamarca"),
            c("25281","Fosca","Cundinamarca"),
            c("25286","Funza","Cundinamarca"),
            c("25288","Fúquene","Cundinamarca"),
            c("25290","Fusagasugá","Cundinamarca"),
            c("25293","Gachalá","Cundinamarca"),
            c("25295","Gachancipá","Cundinamarca"),
            c("25297","Gachetá","Cundinamarca"),
            c("25299","Gama","Cundinamarca"),
            c("25307","Girardot","Cundinamarca"),
            c("25312","Granada","Cundinamarca"),
            c("25317","Guachetá","Cundinamarca"),
            c("25320","Guaduas","Cundinamarca"),
            c("25322","Guasca","Cundinamarca"),
            c("25324","Guataquí","Cundinamarca"),
            c("25326","Guatavita","Cundinamarca"),
            c("25328","Guayabal de Síquima","Cundinamarca"),
            c("25335","Guayabetal","Cundinamarca"),
            c("25339","Gutiérrez","Cundinamarca"),
            c("25368","Jerusalén","Cundinamarca"),
            c("25372","Junín","Cundinamarca"),
            c("25377","La Calera","Cundinamarca"),
            c("25386","La Mesa","Cundinamarca"),
            c("25394","La Palma","Cundinamarca"),
            c("25398","La Peña","Cundinamarca"),
            c("25402","La Vega","Cundinamarca"),
            c("25407","Lenguazaque","Cundinamarca"),
            c("25426","Macheta","Cundinamarca"),
            c("25430","Madrid","Cundinamarca"),
            c("25436","Manta","Cundinamarca"),
            c("25438","Medina","Cundinamarca"),
            c("25473","Mosquera","Cundinamarca"),
            c("25483","Nariño","Cundinamarca"),
            c("25486","Nemocón","Cundinamarca"),
            c("25488","Nilo","Cundinamarca"),
            c("25489","Nimaima","Cundinamarca"),
            c("25491","Nocaima","Cundinamarca"),
            c("25513","Venecia","Cundinamarca"),
            c("25518","Pacho","Cundinamarca"),
            c("25524","Paime","Cundinamarca"),
            c("25530","Pandi","Cundinamarca"),
            c("25535","Paratebueno","Cundinamarca"),
            c("25537","Pasca","Cundinamarca"),
            c("25572","Puerto Salgar","Cundinamarca"),
            c("25580","Pulí","Cundinamarca"),
            c("25592","Quebradanegra","Cundinamarca"),
            c("25594","Quetame","Cundinamarca"),
            c("25596","Quipile","Cundinamarca"),
            c("25599","Apulo","Cundinamarca"),
            c("25612","Ricaurte","Cundinamarca"),
            c("25645","San Antonio del Tequendama","Cundinamarca"),
            c("25649","San Bernardo","Cundinamarca"),
            c("25653","San Cayetano","Cundinamarca"),
            c("25658","San Francisco","Cundinamarca"),
            c("25662","San Juan de Río Seco","Cundinamarca"),
            c("25718","Sasaima","Cundinamarca"),
            c("25736","Sesquilé","Cundinamarca"),
            c("25740","Sibaté","Cundinamarca"),
            c("25743","Silvania","Cundinamarca"),
            c("25745","Simijaca","Cundinamarca"),
            c("25754","Soacha","Cundinamarca"),
            c("25758","Sopó","Cundinamarca"),
            c("25769","Subachoque","Cundinamarca"),
            c("25772","Suesca","Cundinamarca"),
            c("25777","Supatá","Cundinamarca"),
            c("25779","Susa","Cundinamarca"),
            c("25781","Sutatausa","Cundinamarca"),
            c("25785","Tabio","Cundinamarca"),
            c("25793","Tausa","Cundinamarca"),
            c("25797","Tena","Cundinamarca"),
            c("25799","Tenjo","Cundinamarca"),
            c("25805","Tibacuy","Cundinamarca"),
            c("25807","Tibirita","Cundinamarca"),
            c("25815","Tocaima","Cundinamarca"),
            c("25817","Tocancipá","Cundinamarca"),
            c("25823","Topaipí","Cundinamarca"),
            c("25839","Ubalá","Cundinamarca"),
            c("25841","Ubaque","Cundinamarca"),
            c("25843","Villa de San Diego de Ubate","Cundinamarca"),
            c("25845","Une","Cundinamarca"),
            c("25851","Útica","Cundinamarca"),
            c("25862","Vergara","Cundinamarca"),
            c("25867","Vianí","Cundinamarca"),
            c("25871","Villagómez","Cundinamarca"),
            c("25873","Villapinzón","Cundinamarca"),
            c("25875","Villeta","Cundinamarca"),
            c("25878","Viotá","Cundinamarca"),
            c("25885","Yacopí","Cundinamarca"),
            c("25898","Zipacón","Cundinamarca"),
            c("25899","Zipaquirá","Cundinamarca"),
            // ── Bogotá D.C. (11) ─────────────────────────────────────
            c("11001","Bogotá D.C.","Bogotá D.C."),
            // ── Guainía (94) ──────────────────────────────────────────
            c("94001","Inírida","Guainía"),
            c("94343","Barranco Minas","Guainía"),
            c("94663","Mapiripana","Guainía"),
            c("94883","San Felipe","Guainía"),
            c("94884","Puerto Colombia","Guainía"),
            c("94885","La Guadalupe","Guainía"),
            c("94886","Cacahual","Guainía"),
            c("94887","Pana Pana","Guainía"),
            c("94888","Morichal","Guainía"),
            // ── Guajira (44) — ACTIVO ─────────────────────────────────
            c("44001","Riohacha","La Guajira"),
            c("44035","Albania","La Guajira"),
            c("44078","Barrancas","La Guajira"),
            c("44090","Dibulla","La Guajira"),
            c("44098","Distracción","La Guajira"),
            c("44110","El Molino","La Guajira"),
            c("44143","Fonseca","La Guajira"),
            c("44206","Hatonuevo","La Guajira"),
            c("44378","La Jagua del Pilar","La Guajira"),
            c("44420","Maicao","La Guajira"),
            c("44430","Manaure","La Guajira"),
            c("44560","Páez","La Guajira"),
            c("44650","San Juan del Cesar","La Guajira"),
            c("44847","Uribia","La Guajira"),
            c("44855","Urumita","La Guajira"),
            c("44874","Villanueva","La Guajira"),
            // ── Guaviare (95) ─────────────────────────────────────────
            c("95001","San José del Guaviare","Guaviare"),
            c("95015","Calamar","Guaviare"),
            c("95025","El Retorno","Guaviare"),
            c("95200","Miraflores","Guaviare"),
            // ── Huila (41) ────────────────────────────────────────────
            c("41001","Neiva","Huila"),
            c("41006","Acevedo","Huila"),
            c("41013","Agrado","Huila"),
            c("41016","Aipe","Huila"),
            c("41020","Algeciras","Huila"),
            c("41026","Altamira","Huila"),
            c("41078","Baraya","Huila"),
            c("41132","Campoalegre","Huila"),
            c("41206","Colombia","Huila"),
            c("41244","Elías","Huila"),
            c("41298","Garzón","Huila"),
            c("41306","Gigante","Huila"),
            c("41319","Guadalupe","Huila"),
            c("41349","Hobo","Huila"),
            c("41357","Iquira","Huila"),
            c("41359","Isnos","Huila"),
            c("41378","La Argentina","Huila"),
            c("41396","La Plata","Huila"),
            c("41483","Nátaga","Huila"),
            c("41503","Oporapa","Huila"),
            c("41518","Paicol","Huila"),
            c("41524","Palermo","Huila"),
            c("41530","Palestina","Huila"),
            c("41548","Pital","Huila"),
            c("41551","Pitalito","Huila"),
            c("41615","Rivera","Huila"),
            c("41660","Saladoblanco","Huila"),
            c("41668","San Agustín","Huila"),
            c("41676","Santa María","Huila"),
            c("41770","Suaza","Huila"),
            c("41791","Tarqui","Huila"),
            c("41797","Tesalia","Huila"),
            c("41799","Tello","Huila"),
            c("41801","Teruel","Huila"),
            c("41807","Timaná","Huila"),
            c("41872","Villavieja","Huila"),
            c("41885","Yaguará","Huila"),
            // ── Magdalena (47) — ACTIVO ───────────────────────────────
            c("47001","Santa Marta","Magdalena"),
            c("47030","Algarrobo","Magdalena"),
            c("47053","Aracataca","Magdalena"),
            c("47058","Arauca","Magdalena"),
            c("47161","Cerro de San Antonio","Magdalena"),
            c("47170","Chivolo","Magdalena"),
            c("47189","Ciénaga","Magdalena"),
            c("47205","Concordia","Magdalena"),
            c("47245","El Banco","Magdalena"),
            c("47258","El Piñón","Magdalena"),
            c("47268","El Retén","Magdalena"),
            c("47288","Fundación","Magdalena"),
            c("47318","Guamal","Magdalena"),
            c("47460","Nueva Granada","Magdalena"),
            c("47541","Pedraza","Magdalena"),
            c("47545","Pijiño del Carmen","Magdalena"),
            c("47551","Pivijay","Magdalena"),
            c("47555","Plato","Magdalena"),
            c("47570","Puebloviejo","Magdalena"),
            c("47605","Remolino","Magdalena"),
            c("47660","Sabanas de San Ángel","Magdalena"),
            c("47675","Salamina","Magdalena"),
            c("47692","San Sebastián de Buenavista","Magdalena"),
            c("47703","San Zenón","Magdalena"),
            c("47707","Santa Ana","Magdalena"),
            c("47720","Santa Bárbara de Pinto","Magdalena"),
            c("47745","Sitionuevo","Magdalena"),
            c("47798","Tenerife","Magdalena"),
            c("47960","Zapayán","Magdalena"),
            c("47980","Zona Bananera","Magdalena"),
            // ── Meta (50) ─────────────────────────────────────────────
            c("50001","Villavicencio","Meta"),
            c("50006","Acacías","Meta"),
            c("50110","Barranca de Upía","Meta"),
            c("50124","Cabuyaro","Meta"),
            c("50150","Castilla la Nueva","Meta"),
            c("50223","Cubarral","Meta"),
            c("50226","Cumaral","Meta"),
            c("50245","El Calvario","Meta"),
            c("50251","El Castillo","Meta"),
            c("50270","El Dorado","Meta"),
            c("50287","Fuente de Oro","Meta"),
            c("50313","Granada","Meta"),
            c("50318","Guamal","Meta"),
            c("50325","Mapiripán","Meta"),
            c("50330","Mesetas","Meta"),
            c("50350","La Macarena","Meta"),
            c("50370","Uribe","Meta"),
            c("50400","Lejanías","Meta"),
            c("50450","Puerto Concordia","Meta"),
            c("50568","Puerto Gaitán","Meta"),
            c("50573","Puerto López","Meta"),
            c("50577","Puerto Lleras","Meta"),
            c("50590","Puerto Rico","Meta"),
            c("50606","Restrepo","Meta"),
            c("50680","San Carlos de Guaroa","Meta"),
            c("50683","San Juan de Arama","Meta"),
            c("50686","San Juanito","Meta"),
            c("50689","San Martín","Meta"),
            c("50711","Vistahermosa","Meta"),
            // ── Nariño (52) ───────────────────────────────────────────
            c("52001","Pasto","Nariño"),
            c("52019","Albán","Nariño"),
            c("52022","Aldana","Nariño"),
            c("52036","Ancuyá","Nariño"),
            c("52051","Arboleda","Nariño"),
            c("52079","Barbacoas","Nariño"),
            c("52083","Belén","Nariño"),
            c("52110","Buesaco","Nariño"),
            c("52203","Colón","Nariño"),
            c("52207","Consacá","Nariño"),
            c("52210","Contadero","Nariño"),
            c("52215","Córdoba","Nariño"),
            c("52224","Cuaspud","Nariño"),
            c("52227","Cumbal","Nariño"),
            c("52233","Cumbitara","Nariño"),
            c("52240","El Charco","Nariño"),
            c("52250","El Peñol","Nariño"),
            c("52254","El Rosario","Nariño"),
            c("52256","El Tablón de Gómez","Nariño"),
            c("52258","El Tambo","Nariño"),
            c("52260","Funes","Nariño"),
            c("52287","Guachucal","Nariño"),
            c("52293","Guaitarilla","Nariño"),
            c("52295","Gualmatán","Nariño"),
            c("52300","Iles","Nariño"),
            c("52302","Imués","Nariño"),
            c("52320","Ipiales","Nariño"),
            c("52352","La Cruz","Nariño"),
            c("52354","La Florida","Nariño"),
            c("52356","La Llanada","Nariño"),
            c("52358","La Tola","Nariño"),
            c("52360","La Unión","Nariño"),
            c("52378","Leiva","Nariño"),
            c("52381","Linares","Nariño"),
            c("52385","Los Andes","Nariño"),
            c("52390","Magüí","Nariño"),
            c("52399","Mallama","Nariño"),
            c("52405","Mosquera","Nariño"),
            c("52411","Nariño","Nariño"),
            c("52418","Olaya Herrera","Nariño"),
            c("52427","Ospina","Nariño"),
            c("52435","Francisco Pizarro","Nariño"),
            c("52473","Policarpa","Nariño"),
            c("52480","Potosí","Nariño"),
            c("52490","Providencia","Nariño"),
            c("52506","Puerres","Nariño"),
            c("52520","Pupiales","Nariño"),
            c("52540","Ricaurte","Nariño"),
            c("52560","Roberto Payán","Nariño"),
            c("52573","Samaniego","Nariño"),
            c("52585","Sandoná","Nariño"),
            c("52612","San Bernardo","Nariño"),
            c("52621","San Lorenzo","Nariño"),
            c("52678","San Pablo","Nariño"),
            c("52683","San Pedro de Cartago","Nariño"),
            c("52685","Santa Bárbara","Nariño"),
            c("52687","Santacruz","Nariño"),
            c("52693","Sapuyes","Nariño"),
            c("52720","Taminango","Nariño"),
            c("52786","Tangua","Nariño"),
            c("52788","San Andrés de Tumaco","Nariño"),
            c("52835","Túquerres","Nariño"),
            c("52838","Yacuanquer","Nariño"),
            // ── Norte de Santander (54) ───────────────────────────────
            c("54001","Cúcuta","Norte de Santander"),
            c("54003","Ábrego","Norte de Santander"),
            c("54051","Arboledas","Norte de Santander"),
            c("54099","Bochalema","Norte de Santander"),
            c("54109","Bucarasica","Norte de Santander"),
            c("54125","Cácota","Norte de Santander"),
            c("54128","Cáchira","Norte de Santander"),
            c("54172","Chinácota","Norte de Santander"),
            c("54174","Chitagá","Norte de Santander"),
            c("54206","Convención","Norte de Santander"),
            c("54223","Cucutilla","Norte de Santander"),
            c("54239","Durania","Norte de Santander"),
            c("54245","El Carmen","Norte de Santander"),
            c("54250","El Tarra","Norte de Santander"),
            c("54261","El Zulia","Norte de Santander"),
            c("54313","Gramalote","Norte de Santander"),
            c("54344","Hacarí","Norte de Santander"),
            c("54347","Herrán","Norte de Santander"),
            c("54377","Labateca","Norte de Santander"),
            c("54385","La Esperanza","Norte de Santander"),
            c("54398","La Playa","Norte de Santander"),
            c("54405","Los Patios","Norte de Santander"),
            c("54418","Lourdes","Norte de Santander"),
            c("54480","Mutiscua","Norte de Santander"),
            c("54498","Ocaña","Norte de Santander"),
            c("54518","Pamplona","Norte de Santander"),
            c("54520","Pamplonita","Norte de Santander"),
            c("54553","Puerto Santander","Norte de Santander"),
            c("54599","Ragonvalia","Norte de Santander"),
            c("54660","Salazar","Norte de Santander"),
            c("54670","San Calixto","Norte de Santander"),
            c("54673","San Cayetano","Norte de Santander"),
            c("54680","Santiago","Norte de Santander"),
            c("54720","Sardinata","Norte de Santander"),
            c("54743","Silos","Norte de Santander"),
            c("54800","Teorama","Norte de Santander"),
            c("54810","Tibú","Norte de Santander"),
            c("54820","Toledo","Norte de Santander"),
            c("54871","Villa Caro","Norte de Santander"),
            c("54874","Villa del Rosario","Norte de Santander"),
            // ── Putumayo (86) ─────────────────────────────────────────
            c("86001","Mocoa","Putumayo"),
            c("86219","Colón","Putumayo"),
            c("86320","Orito","Putumayo"),
            c("86568","Puerto Asís","Putumayo"),
            c("86569","Puerto Caicedo","Putumayo"),
            c("86571","Puerto Guzmán","Putumayo"),
            c("86573","Puerto Leguízamo","Putumayo"),
            c("86749","Sibundoy","Putumayo"),
            c("86755","San Francisco","Putumayo"),
            c("86757","San Miguel","Putumayo"),
            c("86760","Santiago","Putumayo"),
            c("86865","Valle de Guamuez","Putumayo"),
            c("86885","Villagarzón","Putumayo"),
            // ── Quindío (63) ──────────────────────────────────────────
            c("63001","Armenia","Quindío"),
            c("63111","Buenavista","Quindío"),
            c("63130","Calarcá","Quindío"),
            c("63190","Circasia","Quindío"),
            c("63212","Córdoba","Quindío"),
            c("63272","Filandia","Quindío"),
            c("63302","Génova","Quindío"),
            c("63401","La Tebaida","Quindío"),
            c("63470","Montenegro","Quindío"),
            c("63548","Pijao","Quindío"),
            c("63594","Quimbaya","Quindío"),
            c("63690","Salento","Quindío"),
            // ── Risaralda (66) ────────────────────────────────────────
            c("66001","Pereira","Risaralda"),
            c("66045","Apía","Risaralda"),
            c("66075","Balboa","Risaralda"),
            c("66088","Belén de Umbría","Risaralda"),
            c("66170","Dosquebradas","Risaralda"),
            c("66318","Guática","Risaralda"),
            c("66383","La Celia","Risaralda"),
            c("66400","La Virginia","Risaralda"),
            c("66440","Marsella","Risaralda"),
            c("66456","Mistrató","Risaralda"),
            c("66572","Pueblo Rico","Risaralda"),
            c("66594","Quinchía","Risaralda"),
            c("66682","Santa Rosa de Cabal","Risaralda"),
            c("66687","Santuario","Risaralda"),
            // ── San Andrés y Providencia (88) — ACTIVO ────────────────
            c("88001","San Andrés","San Andrés y Providencia"),
            c("88564","Providencia","San Andrés y Providencia"),
            // ── Santander (68) ────────────────────────────────────────
            c("68001","Bucaramanga","Santander"),
            c("68013","Aguada","Santander"),
            c("68020","Albania","Santander"),
            c("68051","Aratoca","Santander"),
            c("68077","Barbosa","Santander"),
            c("68079","Barichara","Santander"),
            c("68081","Barrancabermeja","Santander"),
            c("68092","Betulia","Santander"),
            c("68101","Bolívar","Santander"),
            c("68121","Cabrera","Santander"),
            c("68132","California","Santander"),
            c("68147","Capitanejo","Santander"),
            c("68152","Carcasí","Santander"),
            c("68160","Cepitá","Santander"),
            c("68162","Cerrito","Santander"),
            c("68167","Charalá","Santander"),
            c("68169","Charta","Santander"),
            c("68176","Chima","Santander"),
            c("68179","Chipatá","Santander"),
            c("68190","Cimitarra","Santander"),
            c("68207","Concepción","Santander"),
            c("68209","Confines","Santander"),
            c("68211","Contratación","Santander"),
            c("68217","Coromoro","Santander"),
            c("68229","Curití","Santander"),
            c("68235","El Carmen de Chucurí","Santander"),
            c("68245","El Guacamayo","Santander"),
            c("68250","El Peñón","Santander"),
            c("68255","El Playón","Santander"),
            c("68264","Encino","Santander"),
            c("68266","Enciso","Santander"),
            c("68271","Florián","Santander"),
            c("68276","Floridablanca","Santander"),
            c("68296","Galán","Santander"),
            c("68298","Gámbita","Santander"),
            c("68307","Girón","Santander"),
            c("68318","Guacamayo","Santander"),
            c("68320","Guapotá","Santander"),
            c("68322","Guavatá","Santander"),
            c("68324","Güepsa","Santander"),
            c("68327","Hato","Santander"),
            c("68344","Jesús María","Santander"),
            c("68368","Jordán","Santander"),
            c("68370","La Belleza","Santander"),
            c("68377","Landázuri","Santander"),
            c("68385","La Paz","Santander"),
            c("68397","Lebrija","Santander"),
            c("68406","Los Santos","Santander"),
            c("68418","Macaravita","Santander"),
            c("68425","Málaga","Santander"),
            c("68432","Matanza","Santander"),
            c("68444","Mogotes","Santander"),
            c("68468","Molagavita","Santander"),
            c("68498","Ocamonte","Santander"),
            c("68500","Oiba","Santander"),
            c("68502","Onzaga","Santander"),
            c("68522","Palmar","Santander"),
            c("68524","Palmas del Socorro","Santander"),
            c("68533","Páramo","Santander"),
            c("68547","Piedecuesta","Santander"),
            c("68549","Pinchote","Santander"),
            c("68572","Puente Nacional","Santander"),
            c("68573","Puerto Parra","Santander"),
            c("68575","Puerto Wilches","Santander"),
            c("68615","Rionegro","Santander"),
            c("68655","Sabana de Torres","Santander"),
            c("68669","San Andrés","Santander"),
            c("68673","San Benito","Santander"),
            c("68679","San Gil","Santander"),
            c("68682","San Joaquín","Santander"),
            c("68684","San José de Miranda","Santander"),
            c("68686","San Miguel","Santander"),
            c("68689","San Vicente de Chucurí","Santander"),
            c("68705","Santa Bárbara","Santander"),
            c("68720","Santa Helena del Opón","Santander"),
            c("68745","Simacota","Santander"),
            c("68755","Socorro","Santander"),
            c("68770","Suaita","Santander"),
            c("68773","Sucre","Santander"),
            c("68780","Suratá","Santander"),
            c("68820","Tona","Santander"),
            c("68855","Valle de San José","Santander"),
            c("68861","Vélez","Santander"),
            c("68867","Vetas","Santander"),
            c("68872","Villanueva","Santander"),
            c("68895","Zapatoca","Santander"),
            // ── Sucre (70) — ACTIVO ───────────────────────────────────
            c("70001","Sincelejo","Sucre"),
            c("70110","Buenavista","Sucre"),
            c("70124","Caimito","Sucre"),
            c("70204","Coloso","Sucre"),
            c("70215","Corozal","Sucre"),
            c("70221","Coveñas","Sucre"),
            c("70230","Chalán","Sucre"),
            c("70233","El Roble","Sucre"),
            c("70235","Galeras","Sucre"),
            c("70265","Guaranda","Sucre"),
            c("70400","La Unión","Sucre"),
            c("70418","Los Palmitos","Sucre"),
            c("70429","Majagual","Sucre"),
            c("70473","Morroa","Sucre"),
            c("70508","Ovejas","Sucre"),
            c("70523","Palmito","Sucre"),
            c("70670","Sampués","Sucre"),
            c("70678","San Benito Abad","Sucre"),
            c("70702","San Juan de Betulia","Sucre"),
            c("70708","San Marcos","Sucre"),
            c("70713","San Onofre","Sucre"),
            c("70717","San Pedro","Sucre"),
            c("70742","San Luis de Sincé","Sucre"),
            c("70771","Since","Sucre"),
            c("70820","Santiago de Tolú","Sucre"),
            c("70823","Tolú Viejo","Sucre"),
            // ── Tolima (73) ───────────────────────────────────────────
            c("73001","Ibagué","Tolima"),
            c("73024","Alpujarra","Tolima"),
            c("73026","Alvarado","Tolima"),
            c("73030","Ambalema","Tolima"),
            c("73043","Anzoátegui","Tolima"),
            c("73055","Armero","Tolima"),
            c("73067","Ataco","Tolima"),
            c("73124","Cajamarca","Tolima"),
            c("73148","Carmen de Apicalá","Tolima"),
            c("73152","Casabianca","Tolima"),
            c("73168","Chaparral","Tolima"),
            c("73200","Coello","Tolima"),
            c("73217","Coyaima","Tolima"),
            c("73226","Cunday","Tolima"),
            c("73236","Dolores","Tolima"),
            c("73268","Espinal","Tolima"),
            c("73270","Falan","Tolima"),
            c("73275","Flandes","Tolima"),
            c("73283","Fresno","Tolima"),
            c("73319","Guamo","Tolima"),
            c("73347","Herveo","Tolima"),
            c("73349","Honda","Tolima"),
            c("73352","Icononzo","Tolima"),
            c("73408","Lérida","Tolima"),
            c("73411","Líbano","Tolima"),
            c("73443","Mariquita","Tolima"),
            c("73449","Melgar","Tolima"),
            c("73461","Murillo","Tolima"),
            c("73483","Natagaima","Tolima"),
            c("73504","Ortega","Tolima"),
            c("73520","Palocabildo","Tolima"),
            c("73547","Piedras","Tolima"),
            c("73555","Planadas","Tolima"),
            c("73563","Prado","Tolima"),
            c("73585","Purificación","Tolima"),
            c("73616","Rioblanco","Tolima"),
            c("73622","Roncesvalles","Tolima"),
            c("73624","Rovira","Tolima"),
            c("73671","Saldaña","Tolima"),
            c("73675","San Antonio","Tolima"),
            c("73678","San Luis","Tolima"),
            c("73686","Santa Isabel","Tolima"),
            c("73770","Suárez","Tolima"),
            c("73854","Valle de San Juan","Tolima"),
            c("73861","Venadillo","Tolima"),
            c("73870","Villahermosa","Tolima"),
            c("73873","Villarrica","Tolima"),
            // ── Valle del Cauca (76) ──────────────────────────────────
            c("76001","Cali","Valle del Cauca"),
            c("76020","Alcalá","Valle del Cauca"),
            c("76036","Andalucía","Valle del Cauca"),
            c("76041","Ansermanuevo","Valle del Cauca"),
            c("76054","Argelia","Valle del Cauca"),
            c("76100","Bolívar","Valle del Cauca"),
            c("76109","Buenaventura","Valle del Cauca"),
            c("76111","Guadalajara de Buga","Valle del Cauca"),
            c("76113","Bugalagrande","Valle del Cauca"),
            c("76122","Caicedonia","Valle del Cauca"),
            c("76126","Calima","Valle del Cauca"),
            c("76130","Candelaria","Valle del Cauca"),
            c("76147","Cartago","Valle del Cauca"),
            c("76233","Dagua","Valle del Cauca"),
            c("76243","El Águila","Valle del Cauca"),
            c("76246","El Cairo","Valle del Cauca"),
            c("76248","El Cerrito","Valle del Cauca"),
            c("76250","El Dovio","Valle del Cauca"),
            c("76275","Florida","Valle del Cauca"),
            c("76306","Ginebra","Valle del Cauca"),
            c("76318","Guacarí","Valle del Cauca"),
            c("76364","Jamundí","Valle del Cauca"),
            c("76377","La Cumbre","Valle del Cauca"),
            c("76400","La Unión","Valle del Cauca"),
            c("76403","La Victoria","Valle del Cauca"),
            c("76497","Obando","Valle del Cauca"),
            c("76520","Palmira","Valle del Cauca"),
            c("76563","Pradera","Valle del Cauca"),
            c("76606","Restrepo","Valle del Cauca"),
            c("76616","Riofrío","Valle del Cauca"),
            c("76622","Roldanillo","Valle del Cauca"),
            c("76670","San Pedro","Valle del Cauca"),
            c("76736","Sevilla","Valle del Cauca"),
            c("76823","Toro","Valle del Cauca"),
            c("76828","Trujillo","Valle del Cauca"),
            c("76834","Tuluá","Valle del Cauca"),
            c("76845","Ulloa","Valle del Cauca"),
            c("76863","Versalles","Valle del Cauca"),
            c("76869","Vijes","Valle del Cauca"),
            c("76890","Yotoco","Valle del Cauca"),
            c("76892","Yumbo","Valle del Cauca"),
            c("76895","Zarzal","Valle del Cauca"),
            // ── Vaupés (97) ───────────────────────────────────────────
            c("97001","Mitú","Vaupés"),
            c("97161","Carurú","Vaupés"),
            c("97511","Pacoa","Vaupés"),
            c("97666","Taraira","Vaupés"),
            c("97777","Papunaua","Vaupés"),
            c("97889","Yavaraté","Vaupés"),
            // ── Vichada (99) ──────────────────────────────────────────
            c("99001","Puerto Carreño","Vichada"),
            c("99524","La Primavera","Vichada"),
            c("99624","Santa Rosalía","Vichada"),
            c("99773","Cumaribo","Vichada")
        );
    }
}
